[package]
name = "react18"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
  "packages/react",
  "packages/react-dom",
  "packages/react-noop",
  "packages/react-reconciler",
  "packages/scheduler",
  "packages/shared",
]
