name: Rust

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: {owner}/{repo}@ref
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
